### ISSUE TITLE
issue when starting broker

### ISSUE THREAD

**Issue by poblin-orange** [18F/concourse-broker#19]
Hello,
while trying current master version, i get this error when broker start.

```
2017-08-14T16:28:50.83+0000 [APP/PROC/WEB/0] OUT Using log level INFO
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR panic: runtime error: invalid memory address or nil pointer dereference
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55f3675550dd]
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR goroutine 14 [running]:
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR panic(0x55f367a8b1a0, 0xc42000c0a0)
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR        /tmp/app/.cloudfoundry/0/go1.7.5/go/src/runtime/panic.go:500 +0x1a5
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR github.com/18F/concourse-broker/concourse.(*concourseClient).UpdateTeams.func1(0xc420118420, 0xc4200ce2a0, 0x55f367c847a0, 0xc4204041c0, 0x1, 0xc4203fa33c, 0x4, 0x0, 0x0)
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR        /tmp/gobuildpack.gopath936462768/.go/src/github.com/18F/concourse-broker/concourse/concourse.go:147 +0xdd
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR created by github.com/18F/concourse-broker/concourse.(*concourseClient).UpdateTeams
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] ERR        /tmp/gobuildpack.gopath936462768/.go/src/github.com/18F/concourse-broker/concourse/concourse.go:170 +0x1f0
2017-08-14T16:28:50.94+0000 [APP/PROC/WEB/0] OUT Exit status 2
2017-08-14T16:28:50.95+0000 [CELL/0] OUT Exit status 0
```
Broker is running as a cf app, and i set the env var which exact values
```
bash-4.1$ cf env concourse-broker                                                                                   
..
User-Provided:
ADMIN_PASSWORD: zzz
ADMIN_USERNAME: atc
AUTH_URL: https://login.nd-preprod-cfapi.itn.intraorange/oauth/authorize
BROKER_PASSWORD: wwwww
BROKER_USERNAME: concourse-aas-broker
CF_URL: https://api.nd-preprod-cfapi.itn.intraorange/
CLIENT_ID: concourse-aas
CLIENT_SECRET: xxxxxxxx
CONCOURSE_URL: https://elpaaso-concourse-dev.nd-preprod-cfapi.itn.intraorange
GO_INSTALL_PACKAGE_SPEC: github.com/18F/concourse-broker/cmd/concourse-broker
TOKEN_URL: https://uaa.nd-preprod-cfapi.itn.intraorange/oauth/token

No running env variables have been set

No staging env variables have been set

```
Any idea what could prevent the broker from starting ?

**Comment by patro158** [comment]
Hi @poblin-orange ,
Were you able to resolve this issue? I am facing a similar issue.
